mqtt:
  broker: mqtt://192.168.3.10:1883

topics:
  - subscribe: "shellies/shellypro3em-0cb815fd5bac/status/em:0"
    transform:
      jsonPath: "$.total_act_power"
      outputFormat: "%.0f W"
    publish: "awtrix_b77810/custom/house power"
    icon: "redplug"
topics_accumulated:
  - group: "Solar"
    publish: "awtrix_b77810/custom/solar power"
    icon: "ani_sun"
    operation: sum
    outputFormat: "%.0f W"
    ignore:
      lessThan: 2.0
    topics:
      - subscribe: "shellies/shellypro4pm-ec62609fdd48/status/switch:2"
        transform:
          jsonPath: "$.apower"
          invert: true
      - subscribe: "shellies/shellyplusplugs-a0a3b3e8c4c8/status/switch:0"
        transform:
          jsonPath: "$.apower"
