mqtt:
  broker: mqtt://192.168.1.10:1883

topics:
  - subscribe: "shellies/shellypro3em-00000000/status/em:0"
    transform:
      jsonPath: "$.total_act_power"
      round: toInteger
      outputFormat: "%v W"
    publish: "awtrix_b00000/custom/house power"