mqtt:
  broker: mqtt://192.168.1.1:1883

topics:
  - subscribe: "shellies/shellypro3em-0000000000/status/em:0"
    transform:
      jsonPath: "$.total_act_power"
      outputFormat: "%.0f W"
    publish: "awtrix_0000000000/custom/house power"
    icon: "redplug"
topics_accumulated:
  - group: "Solar"
    publish: "awtrix_000000000/custom/solar power"
    icon: "ani_sun"
    operation: sum
    outputFormat: "%.0f W"
    ignore:
      lessThan: 2.0
    topics:
      - subscribe: "shellies/shellypro4pm-000000000000/status/switch:2"
        transform:
          jsonPath: "$.apower"
          invert: true
      - subscribe: "shellies/shellyplusplugs-000000000000/status/switch:0"
        transform:
          jsonPath: "$.apower"

# See https://iot.hdev.io/ and https://gist.github.com/dhcgn/80bb8b748f56475922e204d5b84017e0
http:
  - url: https://iot.hdev.io/d/0000000000000000000000000000000000000000000000000000000/json
    interval_sec: 60
    transform:
      jsonPath: "$.priceInfo.current"
      outputFormat: "%.2f"
    publish: "awtrix_b77810/custom/tibber price"
    icon: "tibber"
  - url: https://iot.hdev.io/d/0000000000000000000000000000000000000000000000000000000/plain-from-base64url/tibber_base64
    interval_sec: 60
    transform:
      jsonPath: "$.data.viewer.homes[0].currentSubscription.priceInfo.current.total"
      outputFormat: "%.4f"
    publish: "awtrix_b77810/custom/tibber price"
    icon: "tibber"