mqtt:
  broker: mqtt://192.168.3.10:1883

dispatcher-entries:
  - name: "Shelly Pro 3EM to topic house power"
    source:
      mqtt:
        topics-to-subscribe: 
          - topic: "shellies/shellypro3em-00000000000000000/status/em:0"
            transform:
              jsonPath: "$.total_act_power"
    topics-to-publish: 
      - topic: "awtrix_demo/custom/house power"
        transform:
          outputFormat: "%.0f W"
    icon: "redplug"
    color-script: |
      function get_color(v) {
        if (v < 500.0) {
          return "#32a852"; // green
        } else if (v < 750.0) {
          return "#FFFFFF"; // white
        } else if (v < 900.0) {
          return "#FFFF00"; // yellow
        } else if (v < 1200.0) {
          return "#FF0000"; // red
        } else {
          return "#FFC0CB"; // pink
        }
      }

  - name: "Solar power to topic solar power"
    source:
      mqtt:
        topics-to-subscribe: 
          - topic: "shellies/shellypro4pm-00000000000000/status/switch:2"
            transform:
              jsonPath: "$.apower"
              invert: true
          - topic: "shellies/shellyplusplugs-000000000000000/status/switch:0"
            transform:
              jsonPath: "$.apower"
    topics-to-publish: 
      - topic: "awtrix_demo/custom/solar power"
        transform:
          outputFormat: "%.0f W"
        filter:       
          ignore-less-than: 2.0
    icon: "ani_sun"
    operation: "sum"

    color-script: |
      function get_color(v) {
        if (v < 100.0) {
          return "#FFFFFF"; // white
        } else if (v < 250.0) {
          return "#FFA500"; // orange
        } else if (v < 500.0) {
          return "#FFFF00"; // yellow
        } else if (v < 750.0) {
          return "#008000"; // green
        } else {
          return "#FFC0CB"; // pink
        }
      }

  - name: "Tibber price from http to topic tibber price"
    source:
      http:
        urls:
          - url: https://iot.hdev.io/d/00000000000000000000000000000000000000000000000000/plain-from-base64url/tibber_base64
            transform:
              jsonPath: "$.data.viewer.homes[0].currentSubscription.priceInfo.current.total"
        interval_sec: 60
    topics-to-publish:
      - topic: "awtrix_demo/custom/tibber price"
        transform:
          outputFormat: "%.4f"
    icon: "tibber"
    color-script: |
      function get_color(v) {
        if (v < 0.20) {
          return "#32a852"; // green
        } else if (v < 0.30) {
          return "#FFFFFF"; // white
        } else if (v < 0.40) {
          return "#FFFF00"; // yellow
        } else if (v < 0.50) {
          return "#FF0000"; // red
        } else {
          return "#FFC0CB"; // pink
        }
      }

  - name: "Tibber price from http to topic tibber price (only current price)"
    source:
      http:
        urls:
          - url: https://iot.hdev.io/d/00000000000000000000000000000000000000000000000000/plain/priceInfo/current
        interval_sec: 60
    topics-to-publish:
      - topic: "awtrix_demo/custom/tibber price current"
        transform:
          outputFormat: "%.4f"
    icon: "tibber"
    color-script: |
      function get_color(v) {
        if (v < 0.20) {
          return "#32a852"; // green
        } else if (v < 0.30) {
          return "#FFFFFF"; // white
        } else if (v < 0.40) {
          return "#FFFF00"; // yellow
        } else if (v < 0.50) {
          return "#FF0000"; // red
        } else {
          return "#FFC0CB"; // pink
        }
      }      