mqtt:
  broker: mqtt://192.168.1.1:1883

topics:
  - subscribe: "shellies/shellypro3em-0000000000/status/em:0"
    transform:
      jsonPath: "$.total_act_power"
      outputFormat: "%.0f W"
    publish: "awtrix_0000000000/custom/house power"
    icon: "redplug"
    color-script: |
      function get_color(v) {
        if (v < 500.0) {
          return "#32a852"; // green
        } else if (v < 750.0) {
          return "#FFFFFF"; // white
        } else if (v < 900.0) {
          return "#FFFF00"; // yellow
        } else if (v < 1200.0) {
          return "#FF0000"; // red
        } else {
          return "#FFC0CB"; // pink
        }
      }
topics_accumulated:
  - group: "Solar"
    publish: "awtrix_000000000/custom/solar power"
    icon: "ani_sun"
    color-script: |
      function get_color(v) {
        if (v < 100) {
          return "#FFFFFF"; // white
        } else if (v < 250) {
          return "#FFA500"; // orange
        } else if (v < 500) {
          return "#FFFF00"; // yellow
        } else if (v < 750) {
          return "#008000"; // green
        } else {
          return "#FFC0CB"; // pink
        }
      }
    operation: sum
    outputFormat: "%.0f W"
    ignore:
      lessThan: 2.0
    topics:
      - subscribe: "shellies/shellypro4pm-000000000000/status/switch:2"
        transform:
          jsonPath: "$.apower"
          invert: true
      - subscribe: "shellies/shellyplusplugs-000000000000/status/switch:0"
        transform:
          jsonPath: "$.apower"

# See https://iot.hdev.io/ and https://gist.github.com/dhcgn/80bb8b748f56475922e204d5b84017e0
http:
  - url: https://iot.hdev.io/d/0000000000000000000000000000000000000000000000000000000/json
    interval_sec: 60
    transform:
      jsonPath: "$.priceInfo.current"
      outputFormat: "%.2f"
    publish: "awtrix_b77810/custom/tibber price"
    icon: "tibber"
  - url: https://iot.hdev.io/d/0000000000000000000000000000000000000000000000000000000/plain-from-base64url/tibber_base64
    interval_sec: 60
    transform:
      jsonPath: "$.data.viewer.homes[0].currentSubscription.priceInfo.current.total"
      outputFormat: "%.4f"
    publish: "awtrix_b77810/custom/tibber price"
    icon: "tibber"
    color-script: |
      function get_color(v) {
        if (v < 0.20) {
          return "#32a852"; // green
        } else if (v < 0.30) {
          return "#FFFFFF"; // white
        } else if (v < 0.40) {
          return "#FFFF00"; // yellow
        } else if (v < 0.50) {
          return "#FF0000"; // red
        } else {
          return "#FFC0CB"; // pink
        }
      }